### ISSUE TITLE
Users don't get registered in Firebase Authentication

### ISSUE THREAD

**Issue by RoysManfo** [RoysManfo/RoysManfoHub#1]
Email and password get verified, but the user doesn't appear in the Auth section.
It's probably a problem with the JS modules, as I didn't import them as files, but using a CDN.

**Comment by R0ysM** [comment]
# Possible solution?
Ok ... I'll admit it ... I don't know what I'm doing!  
Maybe starting a prodject with a framework and dealing with sensible user information as a beginner, wasn't a great idea.  
  
 Gonna watch some videos on the firebase YT channel and read the documentation to get this user Auth done.  
__#NotASmartMove__
